version: "3.7"

services:
  klik-adzkia-go-whatsapp-fiber:
    restart: always
    tty: true
    build: .
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:${SERVER_PORT}/health"]
      interval: 60s
      timeout: 10s
      start_period: "10s"
      retries: 3
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${DATA_PATH_HOST}/storage:/app/storage:rw
    networks:
      - klik-adzkia-network
    links:
      - "redis:redis"
    depends_on:
      - redis

  redis:
    container_name: redis
    networks:
      - klik-adzkia-network
    image: redis:alpine
    expose:
      - 6379
    volumes:
      - ${DATA_PATH_HOST}/storage/redis:/data:rw

#Docker Networks
networks:
  klik-adzkia-network:
    driver: bridge
