.PHONY: test security run stop

WHATSAPP_CLIENT_NAME_SHORT = "Klik Adzkia Whatsapp"
WHATSAPP_CLIENT_NAME_LONG = "Klik Adzkia Whatsapp REST Api"
SERVER_KEY = "npjgxbzkroedjcotqxhmglzajebxolta"
SERVER_PORT = 3000
SERVER_URL = "0.0.0.0:$(SERVER_PORT)"
SERVER_READ_TIMEOUT = 60

DB_HOST = 127.0.0.1
DB_USERNAME = "root"
DB_PASSWORD = ""
DB_NAME = "klik-adzkia"
DB_PORT = 3306

BASIC_AUTH_USERNAME = "yusriahmad2@gmail.com"
BASIC_AUTH_PASSWORD = "ahmadyusri"

JWT_SECRET_KEY = "secretOfJwt"
JWT_SECRET_KEY_EXPIRE_MINUTES = 43200
WHATSAPP_CLIENT_VERSION_MAJOR = 2
WHATSAPP_CLIENT_VERSION_MINOR = 2126
WHATSAPP_CLIENT_VERSION_BUILD = 11
WHATSAPP_CLIENT_SESSION_PATH = "./storage"

BUILD_DIR = $(PWD)/app

security:
	gosec -quiet ./...

test: security
	go test -v -timeout 30s -coverprofile=cover.out -cover ./...
	go tool cover -func=cover.out

swag:
	swag init

docker_build_image:
	docker build -t klik-adzkia-go-whatsapp-fiber .

docker_run_image:
	docker run -d \
		--name klik-adzkia-go-whatsapp-fiber-c \
		--restart always \
		-e WHATSAPP_CLIENT_NAME_SHORT=$(WHATSAPP_CLIENT_NAME_SHORT) \
		-e WHATSAPP_CLIENT_NAME_LONG=$(WHATSAPP_CLIENT_NAME_LONG) \
		-e SERVER_KEY=$(SERVER_KEY) \
		-p $(SERVER_PORT):$(SERVER_PORT) \
		-e SERVER_URL=$(SERVER_URL) \
		-e SERVER_PORT=$(SERVER_PORT) \
		-e SERVER_READ_TIMEOUT=$(SERVER_READ_TIMEOUT) \
		-e DB_HOST=$(DB_HOST) \
		-e DB_USERNAME=$(DB_USERNAME) \
		-e DB_PASSWORD=$(DB_PASSWORD) \
		-e DB_NAME=$(DB_NAME) \
		-e DB_PORT=$(DB_PORT) \
		-e BASIC_AUTH_USERNAME=$(BASIC_AUTH_USERNAME) \
		-e BASIC_AUTH_PASSWORD=$(BASIC_AUTH_PASSWORD) \
		-e JWT_SECRET_KEY=$(JWT_SECRET_KEY) \
		-e JWT_SECRET_KEY_EXPIRE_MINUTES=$(JWT_SECRET_KEY_EXPIRE_MINUTES) \
		-e WHATSAPP_CLIENT_VERSION_MAJOR=$(WHATSAPP_CLIENT_VERSION_MAJOR) \
		-e WHATSAPP_CLIENT_VERSION_MINOR=$(WHATSAPP_CLIENT_VERSION_MINOR) \
		-e WHATSAPP_CLIENT_VERSION_BUILD=$(WHATSAPP_CLIENT_VERSION_BUILD) \
		-e WHATSAPP_CLIENT_SESSION_PATH=$(WHATSAPP_CLIENT_SESSION_PATH) \
		klik-adzkia-go-whatsapp-fiber

docker_app: docker_build_image docker_run_image

run: swag docker_app

stop:
	docker container stop klik-adzkia-go-whatsapp-fiber-c
	docker container rm klik-adzkia-go-whatsapp-fiber-c
	docker rmi klik-adzkia-go-whatsapp-fiber
